### ISSUE TITLE
[Feature]: Dockerfile addition for easily setting up project locally.

### ISSUE THREAD

**Issue by SahilSinghTomar** [akshat-OwO/syllabusx-client#104]
### What feature do you want?

A feature request!

**Comment by SahilSinghTomar** [comment]
I can solve this issue. can you please assign it to me

**Comment by akshat-OwO** [comment]
go ahead

**Comment by akshat-OwO** [comment]
@SahilSinghTomar any progress till now?

**Comment by SahilSinghTomar** [comment]
@akshat-OwO I am sorry. I tried to solve it but didn't able to figure it out.

**Comment by akshat-OwO** [comment]
no worries

**Comment by Lakshay-Jain-1** [comment]
I can solve this issue. Please assign it to me. I was learning about Docker, it couldn't have come at a better time.

**Comment by akshat-OwO** [comment]
have fun

**Comment by Lakshay-Jain-1** [comment]
Update: i have uploaded the docker image to docker hub by this name lakshayjain1/syllabusx 
When you run this image you have to do port mapping by the way , here is the command for your convenience
 docker run -it -p 3000:3000 lakshayjain1/syllabusx

future task 
---i have to change image name , 
---image size is 2.8 gb , i will try to decrease this image size
---add you as a collaborator in docker hub ,so that you can change image
---to push my code to your repo , it is my first time contributing to someone else repo


DO YOU WANT ME to change readme file so that i can add commands and make me as a contributor 😊 ??
 
 AND i will do rest of my tasks after my mid  sem is over if it is okay with you !!!

**Comment by akshat-OwO** [comment]
hey @Lakshay-Jain-1,
imo creating a docker image public as your namespace for an opensource project should not be the right thing to do. Instead you should create `Dockerfile` and `docker-compose.yml` files, which then can be used.
And you don't need to be worried about the size of image as it will be only used for developing purposes for devs who have not setup node in their local machine or have different node version.
Keep in mind the volume used should allow hot reloading as well.

You are allowed to change readme and can continue after mid sems

**Comment by akshat-OwO** [comment]
@Lakshay-Jain-1 any progress on this it's been a very long time

**Comment by Lakshay-Jain-1** [comment]
@akshat-OwO
sorry , I forgot to update you on my progress with adding hot reloading to the Dockerized Next.js project.
 Unfortunately, it’s not working at all, and I’ve tried several solutions. I think the issue lies in how I'm mapping the current directory to the container’s working directory.

If you have experience with Docker, could you help me identify where I might be going wrong?

#### Dockerfile

```dockerfile
FROM node:20


RUN npm install -g nodemon


WORKDIR /app


COPY package*.json pnpm-lock.yaml* ./


RUN npm install -g pnpm


RUN pnpm install

COPY . .

EXPOSE 3000


CMD ["nodemon", "--watch", ".", "--exec", "pnpm run dev"]
```

#### Docker Compose File

```yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app                    # Map the entire codebase with /app
      - /app/node_modules          
      - /app/.next                
    command: ["pnpm", "run", "dev"]
```
